version: "3"

volumes:
  neo4j_data:
  neo4j_logs:
  keys_data:

networks:
  inside:
  outside:

services:
  neo4j:
    image: neo4j:latest
    restart: always
    container_name: rideonine_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=${DATABASE_USER}/${DATABASE_PASS}
    networks:
      - inside
    
  sms:
    image: ghcr.io/jadjer/rideonline_sms:latest
    restart: always
    container_name: rideonline_sms
    networks:
      - inside

  keys:
    image: ghcr.io/jadjer/rideonline_keys:latest
    restart: always
    container_name: rideonline_keys
    volumes:
      - keys_data:/keys
    networks:
      - inside

  auth:
    image: ghcr.io/jadjer/rideonline_auth:latest
    restart: always
    depends_on:
      - neo4j
      - sms
      - keys
    volumes:
      - keys_data:/app/keys:ro
    environment:
      - DATABASE_HOST=rideonine_neo4j
      - DATABASE_PORT=7687
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - PUBLIC_KEY_PATH=/app/keys/public_key.pem
      - PRIVATE_KEY_PATH=/app/keys/private_key.pem
      - SMS_SERVICE=http://rideonline_sms:8000/api/v1
      - VIRTUAL_HOST=auth.rideonline.jadjer.by
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=auth.rideonline.jadjer.by
    networks:
      - inside
      - outside

  events:
    image: ghcr.io/jadjer/rideonline_events:latest
    restart: always
    depends_on:
      - neo4j
      - auth
      - keys
    volumes:
      - keys_data:/app/keys:ro
    environment:
      - DATABASE_HOST=rideonine_neo4j
      - DATABASE_PORT=7687
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - PUBLIC_KEY_PATH=/app/keys/public_key.pem
      - VIRTUAL_HOST=events.rideonline.jadjer.by
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=events.rideonline.jadjer.by
    networks:
      - inside
      - outside

  together:
    image: ghcr.io/jadjer/rideonline_together:latest
    restart: always
    depends_on:
      - neo4j
      - auth
      - keys
    volumes:
      - keys_data:/app/keys:ro
    environment:
      - DATABASE_HOST=rideonine_neo4j
      - DATABASE_PORT=7687
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - PUBLIC_KEY_PATH=/app/keys/public_key.pem
      - VIRTUAL_HOST=together.rideonline.jadjer.by
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=together.rideonline.jadjer.by
    networks:
      - inside
      - outside
    
